const {test}=require('node:test');
const assert=require('node:assert/strict');
const {fork}=require('node:child_process');
const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {WebSocket}=require('ws');
test('local server authenticates HTTP and WebSockets; persists custom pipelines',async t=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vibedeck-test-'));
  const child=fork(path.join(__dirname,'../server.js'),[],{env:{...process.env,VIBEDECK_PORT:'0',VIBEDECK_DATA_DIR:dir,VIBEDECK_NO_PANES:'1'},stdio:['ignore','ignore','pipe','ipc']});
  let socket;
  t.after(async()=>{socket?.terminate();child.send({type:'shutdown'});await new Promise(r=>child.once('exit',r));fs.rmSync(dir,{recursive:true,force:true});});
  const url=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('server start timed out')),10000);child.once('message',m=>{clearTimeout(timeout);resolve(m.url);});child.once('error',reject);});
  const origin=new URL(url).origin;
  assert.equal((await fetch(origin)).status,403);
  const login=await fetch(url,{redirect:'manual'});assert.equal(login.status,302);
  const cookie=login.headers.get('set-cookie').split(';')[0];assert.match(login.headers.get('set-cookie'),/HttpOnly/);
  assert.equal((await fetch(origin,{headers:{cookie}})).status,200);
  assert.equal((await fetch(origin,{headers:{cookie,origin:'https://attacker.example'}})).status,403);
  const rejection=await new Promise(resolve=>{const bad=new WebSocket(origin.replace('http:','ws:'),{headers:{cookie,origin:'https://attacker.example'}});bad.on('unexpected-response',(_req,res)=>{resolve(res.statusCode);res.resume();bad.terminate();});bad.on('error',()=>{});});assert.equal(rejection,401);
  socket=new WebSocket(origin.replace('http:','ws:'),{headers:{cookie,origin}});
  const init=await new Promise(resolve=>socket.once('message',m=>resolve(JSON.parse(m))));assert.equal(init.type,'init');
  const saved=new Promise(resolve=>socket.once('message',m=>resolve(JSON.parse(m))));
  socket.send(JSON.stringify({type:'customPipelineSave',definition:{name:'Test chain',steps:[{role:'Plan',kind:'codex',model:'gpt-6-astra'}]}}));
  assert.equal((await saved).items[0].name,'Test chain');assert.equal(JSON.parse(fs.readFileSync(path.join(dir,'data/custom-pipelines.json')))[0].name,'Test chain');
  const provider=require('node:http').createServer((req,res)=>{req.resume();req.on('end',()=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:'Fixture model review'},finish_reason:'stop'}]}));});});
  await new Promise(resolve=>provider.listen(0,'127.0.0.1',resolve));t.after(()=>provider.close());
  const waitMessage=type=>new Promise(resolve=>{const receive=raw=>{const msg=JSON.parse(raw);if(msg.type===type){socket.off('message',receive);resolve(msg);}};socket.on('message',receive);});
  const connectionSaved=waitMessage('connectionSaved');
  socket.send(JSON.stringify({type:'connectionSave',connection:{name:'Fixture local model',baseUrl:`http://127.0.0.1:${provider.address().port}/v1`,protocol:'openai',model:'fixture-model'}}));
  const connectionId=(await connectionSaved).id;
  const completed=new Promise((resolve,reject)=>{const receive=raw=>{const msg=JSON.parse(raw);if(msg.type==='customPipelineStatus'&&['done','error'].includes(msg.state)){socket.off('message',receive);msg.state==='done'?resolve(msg):reject(Error(msg.text));}};socket.on('message',receive);});
  socket.send(JSON.stringify({type:'customPipelineStart',definition:{name:'Local review',steps:[{kind:'api',role:'Review',model:'',connectionId}]},prompt:'Review this sample.'}));
  assert.equal((await completed).outputs[0].text,'Fixture model review');
});

